version: '3.8'
services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
    ports:
      - 5432:5432