version: '3.8'
services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgresql
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgresql